export const semantic = [
  { type: "Location", tag: "Indoor", parent: "NO", label: "Indoor", synonyms: [], description: "Anything that is inside a closed building" },
  { type: "Location", tag: "Building", parent: "Indoor", label: "Building", synonyms: ["Buildings"], description: "" },
  { type: "Location", tag: "Garage", parent: "Building", label: "Garage", synonyms: ["Garages"], description: "" },
  { type: "Location", tag: "Floor", parent: "Indoor", label: "Floor", synonyms: ["Floors"], description: "" },
  { type: "Location", tag: "GroundFloor", parent: "Floor", label: "Ground Floor", synonyms: ["Ground Floors", "Downstairs"], description: "" },
  { type: "Location", tag: "FirstFloor", parent: "Floor", label: "First Floor", synonyms: ["First Floors", "Upstairs"], description: "" },
  { type: "Location", tag: "Attic", parent: "Floor", label: "Attic", synonyms: ["Attics"], description: "" },
  { type: "Location", tag: "Basement", parent: "Floor", label: "Basement", synonyms: ["Basements", "Cellar", "Cellars"], description: "" },
  { type: "Location", tag: "Corridor", parent: "Indoor", label: "Corridor", synonyms: ["Corridors"], description: "" },
  { type: "Location", tag: "Room", parent: "Indoor", label: "Room", synonyms: ["Rooms"], description: "" },
  { type: "Location", tag: "Bedroom", parent: "Room", label: "Bedroom", synonyms: ["Bedrooms"], description: "" },
  { type: "Location", tag: "Kitchen", parent: "Room", label: "Kitchen", synonyms: ["Kitchens"], description: "" },
  { type: "Location", tag: "Bathroom", parent: "Room", label: "Bathroom", synonyms: ["Bathrooms", "Bath", "Baths"], description: "" },
  { type: "Location", tag: "LivingRoom", parent: "Room", label: "Living Room", synonyms: ["Living Rooms"], description: "" },
  { type: "Location", tag: "Outdoor", parent: "NO", label: "Outdoor", synonyms: [], description: "" },
  { type: "Location", tag: "Garden", parent: "Outdoor", label: "Garden", synonyms: ["Gardens"], description: "" },
  { type: "Location", tag: "Terrace", parent: "Outdoor", label: "Terrace", synonyms: ["Terraces", "Deck", "Decks"], description: "" },
  { type: "Location", tag: "Carport", parent: "Outdoor", label: "Carport", synonyms: ["Carports"], description: "" },
  { type: "Property", tag: "Temperature", parent: "NO", label: "Temperature", synonyms: ["Temperatures"], description: "" },
  { type: "Property", tag: "Light", parent: "NO", label: "Light", synonyms: ["Lights", "Lighting"], description: "" },
  { type: "Property", tag: "ColorTemperature", parent: "NO", label: "Color Temperature", synonyms: [], description: "" },
  { type: "Property", tag: "Humidity", parent: "NO", label: "Humidity", synonyms: ["Moisture"], description: "" },
  { type: "Property", tag: "Presence", parent: "NO", label: "Presence", synonyms: [], description: "" },
  { type: "Property", tag: "Pressure", parent: "NO", label: "Pressure", synonyms: [], description: "" },
  { type: "Property", tag: "Smoke", parent: "NO", label: "Smoke", synonyms: [], description: "" },
  { type: "Property", tag: "Noise", parent: "NO", label: "Noise", synonyms: [], description: "" },
  { type: "Property", tag: "Rain", parent: "NO", label: "Rain", synonyms: [], description: "" },
  { type: "Property", tag: "Wind", parent: "NO", label: "Wind", synonyms: [], description: "" },
  { type: "Property", tag: "Water", parent: "NO", label: "Water", synonyms: [], description: "" },
  { type: "Property", tag: "CO2", parent: "NO", label: "CO2", synonyms: ["Carbon Dioxide"], description: "" },
  { type: "Property", tag: "CO", parent: "NO", label: "CO", synonyms: ["Carbon Monoxide"], description: "" },
  { type: "Property", tag: "Energy", parent: "NO", label: "Energy", synonyms: [], description: "" },
  { type: "Property", tag: "Power", parent: "NO", label: "Power", synonyms: [], description: "" },
  { type: "Property", tag: "Voltage", parent: "NO", label: "Voltage", synonyms: [], description: "" },
  { type: "Property", tag: "Current", parent: "NO", label: "Current", synonyms: [], description: "" },
  { type: "Property", tag: "Frequency", parent: "NO", label: "Frequency", synonyms: [], description: "" },
  { type: "Property", tag: "Gas", parent: "NO", label: "Gas", synonyms: [], description: "" },
  { type: "Property", tag: "SoundVolume", parent: "NO", label: "Sound Volume", synonyms: [], description: "" },
  { type: "Property", tag: "Oil", parent: "NO", label: "Oil", synonyms: [], description: "" },
  { type: "Point", tag: "Alarm", parent: "NO", label: "Alarm", synonyms: [], description: "" },
  { type: "Point", tag: "Control", parent: "NO", label: "Control", synonyms: [], description: "" },
  { type: "Point", tag: "Switch", parent: "Control", label: "Switch", synonyms: [], description: "" },
  { type: "Point", tag: "Measurement", parent: "NO", label: "Measurement", synonyms: [], description: "" },
  { type: "Point", tag: "Setpoint", parent: "NO", label: "Setpoint", synonyms: [], description: "" },
  { type: "Point", tag: "Status", parent: "NO", label: "Status", synonyms: [], description: "" },
  { type: "Point", tag: "LowBattery", parent: "Status", label: "LowBattery", synonyms: [], description: "" },
  { type: "Point", tag: "OpenState", parent: "Status", label: "OpenState", synonyms: [], description: "" },
  { type: "Point", tag: "Tampered", parent: "Status", label: "Tampered", synonyms: [], description: "" },
  { type: "Point", tag: "OpenLevel", parent: "Status", label: "OpenLevel", synonyms: [], description: "" },
  { type: "Point", tag: "Tilt", parent: "Status", label: "Tilt", synonyms: [], description: "" },
  { type: "Equipment", tag: "Battery", parent: "NO", label: "Battery", synonyms: ["Batteries"], description: "" },
  { type: "Equipment", tag: "Blinds", parent: "NO", label: "Blinds", synonyms: ["Rollershutter", "Rollershutters", "Roller shutter", "Roller shutters", "Shutter", "Shutters"], description: "" },
  { type: "Equipment", tag: "Camera", parent: "NO", label: "Camera", synonyms: ["Cameras"], description: "" },
  { type: "Equipment", tag: "Car", parent: "NO", label: "Car", synonyms: ["Cars"], description: "" },
  { type: "Equipment", tag: "CleaningRobot", parent: "NO", label: "Cleaning Robot", synonyms: ["Cleaning Robots", "Vacuum robot", "Vacuum robots"], description: "" },
  { type: "Equipment", tag: "Door", parent: "NO", label: "Door", synonyms: ["Doors"], description: "" },
  { type: "Equipment", tag: "FrontDoor", parent: "Door", label: "Front Door", synonyms: ["Front Doors", "Frontdoor", "Frontdoors"], description: "" },
  { type: "Equipment", tag: "GarageDoor", parent: "Door", label: "Garage Door", synonyms: ["Garage Doors"], description: "" },
  { type: "Equipment", tag: "HVAC", parent: "NO", label: "HVAC", synonyms: ["Heating", "Ventilation", "Air Conditioning", "A/C", "A/Cs", "AC"], description: "" },
  { type: "Equipment", tag: "Inverter", parent: "NO", label: "Inverter", synonyms: ["Inverters"], description: "" },
  { type: "Equipment", tag: "LawnMower", parent: "NO", label: "Lawn Mower", synonyms: ["Lawn Mowers"], description: "" },
  { type: "Equipment", tag: "Lightbulb", parent: "NO", label: "Lightbulb", synonyms: ["Lightbulbs", "Bulb", "Bulbs", "Lamp", "Lamps", "Lights", "Lighting"], description: "" },
  { type: "Equipment", tag: "Lock", parent: "NO", label: "Lock", synonyms: ["Locks"], description: "" },
  { type: "Equipment", tag: "MotionDetector", parent: "NO", label: "Motion Detector", synonyms: ["Motion Detectors", "Motion sensor", "Motion sensors"], description: "" },
  { type: "Equipment", tag: "NetworkAppliance", parent: "NO", label: "Network Appliance", synonyms: ["Network Appliances"], description: "" },
  { type: "Equipment", tag: "PowerOutlet", parent: "NO", label: "Power Outlet", synonyms: ["Power Outlets", "Outlet", "Outlets"], description: "" },
  { type: "Equipment", tag: "Projector", parent: "NO", label: "Projector", synonyms: ["Projectors", "Beamer", "Beamers"], description: "" },
  { type: "Equipment", tag: "RadiatorControl", parent: "NO", label: "Radiator Control", synonyms: ["Radiator Controls", "Radiator", "Radiators"], description: "" },
  { type: "Equipment", tag: "Receiver", parent: "NO", label: "Receiver", synonyms: ["Receivers", "Audio Receiver", "Audio Receivers", "AV Receiver", "AV Receivers"], description: "" },
  { type: "Equipment", tag: "RemoteControl", parent: "NO", label: "Remote Control", synonyms: ["Remote Controls"], description: "" },
  { type: "Equipment", tag: "Screen", parent: "NO", label: "Screen", synonyms: ["Screens", "Television", "Televisions", "TV", "TVs"], description: "" },
  { type: "Equipment", tag: "Siren", parent: "NO", label: "Siren", synonyms: ["Sirens"], description: "" },
  { type: "Equipment", tag: "SmokeDetector", parent: "NO", label: "Smoke Detector", synonyms: ["Smoke Detectors"], description: "" },
  { type: "Equipment", tag: "Speaker", parent: "NO", label: "Speaker", synonyms: ["Speakers"], description: "" },
  { type: "Equipment", tag: "Valve", parent: "NO", label: "Valve", synonyms: ["Valves"], description: "" },
  { type: "Equipment", tag: "WallSwitch", parent: "NO", label: "Wall Switch", synonyms: ["Wall Switches"], description: "" },
  { type: "Equipment", tag: "WebService", parent: "NO", label: "Web Service", synonyms: ["Web Services"], description: "" },
  { type: "Equipment", tag: "Window", parent: "NO", label: "Window", synonyms: ["Windows"], description: "" },
  { type: "Equipment", tag: "WhiteGood", parent: "NO", label: "White Good", synonyms: ["White Goods"], description: "" }
];